apiVersion: skaffold/v2alpha3
kind: Config
deploy:
  kubectl:
    manifests:
      - ./k8s/*
build:
  local:
    push: false
  artifacts:
    - image: jubasse/ticketing-auth
      context: .
      docker:
        dockerfile: apps/auth/Dockerfile
      sync:
        manual:
          - src: 'apps/auth/src/**/*.ts'
            dest: .
    - image: jubasse/ticketing-tickets
      context: .
      docker:
        dockerfile: apps/tickets/Dockerfile
      sync:
        manual:
          - src: 'apps/tickets/src/**/*.ts'
            dest: .
    - image: jubasse/ticketing-users
      context: .
      docker:
        dockerfile: apps/users/Dockerfile
      sync:
        manual:
          - src: 'apps/users/**/*.ts'
            dest: .
