apiVersion: apps/v1
kind: Deployment
metadata:
  name: ticketing-kafka-depl
  labels:
    app: ticketing-kafka
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ticketing-kafka
  template:
    metadata:
      labels:
        app: ticketing-kafka
    spec:
      containers:
      - name: ticketing-kafka-broker
        image: confluentinc/cp-kafka:latest
        ports:
        - containerPort: 9092
        env:
        - name: KAFKA_BROKER_ID
          value: "1"
        - name: KAFKA_ZOOKEEPER_CONNECT
          value: 'ticketing-zookeeper-svc:2181'
        - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
          value: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
        - name: KAFKA_ADVERTISED_LISTENERS
          value: PLAINTEXT://:29092,PLAINTEXT_INTERNAL://ticketing-kafka-svc:9092
        - name: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
          value: "1"
        - name: KAFKA_TRANSACTION_STATE_LOG_MIN_ISR
          value: "1"
        - name: KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR
          value: "1"
---
apiVersion: v1
kind: Service
metadata:
  name: ticketing-kafka-svc
spec:
  selector:
    app: ticketing-kafka
  ports:
    - protocol: TCP
      port: 9092
      targetPort: 9092