apiVersion: v1
kind: Service
metadata:
  labels:
    app: ticketing-zookeeper-svc
  name: ticketing-zookeeper-svc
spec:
  type: NodePort
  ports:
    - name: ticketing-zookeeper-port
      port: 2181
      nodePort: 30181
      targetPort: 2181
  selector:
    app: ticketing-zookeeper
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: ticketing-zookeeper
  labels:
    app: ticketing-zookeeper
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ticketing-zookeeper
  serviceName: ticketing-zookeeper
  template:
    metadata:
      labels:
        app: ticketing-zookeeper
    spec:
      containers:
        - image: wurstmeister/zookeeper
          imagePullPolicy: IfNotPresent
          name: ticketing-zookeeper
          ports:
            - containerPort: 2181
  volumeClaimTemplates:
    - metadata:
        name: ticketing-kafka-storage
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 50Mi